### ISSUE TITLE
can I set API_KEY  in docker-compose?

### ISSUE THREAD

**Issue by mangoos2** [nginxinc/docker-nginx-amplify#18] opened 2018-12-08 16:26 UTC
environment:
      - API_KEY:62bce.......
      - AMPLIFY_IMAGENAME:plus-server

it's not working, 
can i use docker-compose to set amplify API_KEY?

**Comment by gdzien** [comment] 2018-12-11 17:59
Hello there,

I am Greg from NGINX Inc. I will be assisting you with this issue going forward. 
This is just to let you know that I am looking into this and should get back to you shortly. 

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/

**Comment by gdzien** [comment] 2018-12-11 19:58
Hello again mangoos2!

I have been looking to reproduce the issue you are having and here are my findings:
1) API_KEY variable can be set in docker compose environment and this is working fine
2) If I try to use this the way you have configured your environment it will not work
3) Example of docker-compose.yml file that works for me:
```
version: "3.3"
services:
  nginx-amplify:
    image: nginx-amplify
    environment:
      API_KEY: my_api_key
```

Please note that in my case I do not use yaml list, but rather simple variable, so please do not use - in front of variable name and please use a space after colon. 

Hopefully this will help you. Please let me know if you have any further questions or if I should close this issue.

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/

**Comment by gdzien** [comment] 2018-12-19 11:35
Hello again,

As I have not heard back from you for over 7 days now I will go ahead and close this issue. Please let me know if you need further assistance.

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/

**Closed by gdzien** 2018-12-19 11:35 UTC
